(lang dune 3.17)
(name my_lamb)
(generate_opam_files true)
(source
 (github dusk/my-lamb))
(authors "Dusk <your-email@example.com>")
(maintainers "Dusk <your-email@example.com>")
(license MIT)
(package
 (name my_lamb)
 (synopsis "A very shitty lambda calculus, extended with new features.")
 (description "A very shitty lambda calculus, extended with new features.")
 (depends ocaml reason linenoise))
